[package]
name = "ci_png_parser"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
ci_core = { path = "../ci-core" }
regex = "1"
lazy_static = "1.4.0"
maplit = "1.0.2"
